services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]