name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build  # Astro builds to ./dist by default

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}   # needs Pages Write
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # change the project name to your Pages project
          command: pages deploy ./dist --project-name=${{ secrets.CF_PAGES_PROJECT }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

